### DISCUSSION TITLE
Cannot define marker in note frontmatter

### DISCUSSION THREAD

**Discussion by x55xaa** [javalent/obsidian-leaflet#448] [Q&A]
Scrolling through the documentation, I came across the [mapmarker](https://github.com/javalent/obsidian-leaflet?tab=readme-ov-file#mapmarker) parameter. I wanted to define a marker in the frontmatter of my note, but the example provided in the docs doesn't seem to work.

**example_note.md**
```
---
location:
  - "32"
  - "-89"
mapmarker:
  icon: user        # Font Awesome icon name.
  color: 00ff00     # Hex color string. Optional.
  layer: false      # Whether or not to layer. Optional.
---
```

**main.md**
````
```leaflet
id: leaflet-map
coordinates: [32, -89]
markerFile: [[example_note]]
```
````

Am I doing something wrong or is this a bug?
