### DISCUSSION TITLE
about an example of marker files

### DISCUSSION THREAD

**Discussion by zhubib1234** [javalent/obsidian-leaflet#70] [Q&A]
Can you give an example of marker files? I don't know the format of the data in the file.

**Comment by valentine195** [comment]
If you click the "export" button, it will generate a CSV file of the current marker data, which you can reference.

**Reply by zhubib1234** [reply]
thanks

**Reply by zhubib1234** [reply]
I tried, but I still couldn't.
This is my text in markerfile.md. What's wrong?

Map With Layered Images,1,-0.04045129399187863,0.029928588308393955,HanLP,[[18.jpg]],xnRJXv
Map With Layered Images,1,-0.04054284672625363,0.033438109792768955,hanLP2.1,[[18.jpg]],zZAQ1w

**Comment by valentine195** [comment]
The marker data CSV has the following format:

| Map ID | Latitude | Longtitude | Marker Type | Marker Layer | Marker ID |
| --- | --- | --- | --- | --- | --- |
|Map With Layered Images|1|-0.04045129399187863,0.029928588308393955|HanLP|[[18.jpg]]| xnRJXv| 
|Map With Layered Images|1|-0.04054284672625363,0.033438109792768955|hanLP2.1的使用|[[18.jpg]]|zZAQ1w |

Additional markers may be added to the map using this format in a CSV file.

Marker ID is optional - if not provided, the map will generate it automatically. **If you use a marker ID that already exists, the existing marker data will be overwritten**.

**Reply by zhubib1234** [reply]
thanks！
Can I use it in MD file? Can only be a CSV file?
I didn't understand the explanation.

“Marker Files, Marker Folders and Marker Tags
These parameters allow you to create markers directly from a list of markdown note files.
A note specified in this manner should have the following frontmatter tags: location: [lat, long] REQUIRED mapmarker: <marker-type> OPTIONAL”

**Reply by valentine195** [reply]
Correct, this feature can only be used with a CSV file.

The [Marker File, Marker Folder and Marker Tag](https://github.com/valentine195/obsidian-leaflet-plugin#marker-files-marker-folders-and-marker-tags) parameters are parameters of the map code block.

Example:

````
```leaflet
markerFile: [[Note]]
markerFolder: Folder/Nested Folder
```
````

This would load `Note` and _all of the notes (including nested!)_ in Folder/Nested Folder and look for the `location` and `mapmarker` frontmatter tags. If a note has that tag, a marker will be created at the location specified in `location` using the marker type specified in `mapmarker` (or default if not used).

**Reply by zhubib1234** [reply]
thanks，Can you give an example of location and mapmaker in note application?

**Reply by valentine195** [reply]
Sure. If you put the following at the top of a note (lets call it Note.md), it will generate metadata for that note:

```
---
location: [5, 10]
mapmarker: <markerType defined in settings>
---
```

If you then have the following block:

````
```leaflet
id: x
markerFile: [[Note]]
```
````

It will create a marker at [5, 10] with the <markerType> icon, auto-linking it to [[Note]]

**Reply by zhubib1234** [reply]
thanks，I finally get it.

**Reply by Moonbase59** [reply]
@zhubib1234: Here’s a rather complicated example of YAML data in a normal note, for you to experiment with (it shows the "Kuhsee" ("cow lake") near Augsburg, Bavaria, Germany):

```yaml
---
location: [48.337838,10.9404818]
mapmarker: Recreation
mapoverlay:
    - [blue, [48.3434334,10.9393137], 20 m, "🅿️ Parkplatz Kuhsee Nord"]
    - [blue, [48.3386505,10.9439455], 20 m, "🅿️ Parkplatz Kuhsee Süd"]
    - [blue, [48.337911,10.944044], 20 m, "🅿️ Parkplatz am Kuhseelauf"]
    - [blue, [48.3360085,10.9431114], 10 m, "🚾 Toilette"]
    - [blue, [48.3356309,10.9396944], 10 m, "🚾 Toilette"]
    - [blue, [48.3389219,10.9380973], 10 m, "🚾 Toilette"]
    - ['rgba(192, 0, 192, .6)', [48.3341375,10.9425521], 20 m, "Grillbereich"]
    - ['rgba(192, 0, 192, .6)', [48.3399471,10.9408536], 20 m, "Kinderspielplatz"]
    - ['rgba(192, 0, 192, .6)', [48.3439827,10.9367596], 50 m, "Hochablass"]
    - ['rgba(192, 0, 192, .6)', [48.343713,10.9376012], 20 m, "🍴 Schwarze Kiste am Hochablass"]
    - ['rgba(192, 0, 192, .6)', [48.3373208,10.9426188], 20 m, "🍴 Imbisshütte am Kuhsee"]
    - ['rgba(192, 0, 192, .6)', [48.3412227,10.9404761], 20 m, "🍴 Kiosk am Kuhsee"]
---
```

Should look on the map like this:

![Auswahl_109](https://user-images.githubusercontent.com/3706922/120944319-2650fa00-c734-11eb-85e0-f1b533bbb430.png)
