### ISSUE TITLE
Change Size of Marker Types

### ISSUE THREAD

**Issue by valentine195** [javalent/obsidian-leaflet#32]
All marker types are currently set to 25px x 25px through CSS.

- [ ] I should be using the [DivIcon > IconSize](https://leafletjs.com/reference-1.7.1.html#divicon) setting when creating a marker to set size, and have an option to change the size of marker types when creating/editing them.
- [ ] I would also like to have transform controls in the Create Marker Modal so that the marker is fully transformable, and not just scalable  

Marker sizes are changeable via CSS:

###### All Markers
```css
.leaflet-div-icon > svg {
    width: 12px !important;
    height: 12px !important;
}
```

###### Specific Type (Marker icon is set to the Font Awesome circle icon)
```css
.leaflet-div-icon > svg.fa-circle {
    width: 12px !important;
    height: 12px !important;
}
```
https://forum.obsidian.md/t/new-plugin-obsidian-leaflet-interactive-maps-in-notes/14752/41?u=valentine.195
