### ISSUE TITLE
[Bug] local links for markers don't work

### ISSUE THREAD

**Issue by Sirs0ri** [javalent/obsidian-leaflet#361]
# Problem Description

Obsidian has the feature where you can leave out the current note's title to link to headings / `^`-anchors inside the current note, this functionality is currently missing from obsidian-leaflet.

Since Obsidian's autocomplete function works inside code blocks, I can type `[[#` inside of a leaflet codeblock, and I'll get the current file's headings as suggestion, e.g. `[[#Main Heading]]` for the example below. The marker created from that link will have a popup with the message `"#Main Heading" is not created yet. Click to create.`

# Example Code:

MyNote.md
```md
#Main Heading

This is a full link, this format will work for markers: [[MyNote#Main Heading]]
This link will work only in obsidian's text, not in markers: [[#Main Heading]]
```

leaflet embed inside MyNote.md:
```yaml
id: test
lat: 1
long: 1
marker: 
  - default, 0, 0, [[MyNote#Main Heading]], This will work
  - default, 0, 1, [[#Main Heading]], This will not
```

# Additional Info

Obsidian Version: 1.1.16
Leaflet Version: 5.2.6  

**Correctly created marker**
![correctly created marker](https://user-images.githubusercontent.com/6765536/229511275-79153903-2680-4364-a2c5-58e9d54ea855.png)

**Marker with broken link**
![marker with broken link](https://user-images.githubusercontent.com/6765536/229511315-47fadb7e-1055-4323-ab4c-6cccf47398c0.png)
